server:
  port: ${PORT}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    password: ${JDBC_DATABASE_PASSWORD}
    username: ${JDBC_DATABASE_USERNAME}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
api:
  info:
    title: Manga API
    version: 1.0.0
    description: Manga API is a web service that provides online information about mangas.
  contact:
    email: mario-dacosta@hotmail.fr
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  uri:
    paths:
      mangas: /api/v1/mangas